/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OnChainRiddle } from "./OnChainRiddle";
export * as factories from "./factories";
export { OnChainRiddle__factory } from "./factories/OnChainRiddle__factory";
